#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration
i=0
while [ $i -lt 11 ]; do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
